framework:
    validation:
        enable_attributes: true
        email_validation_mode: html5
        not_compromised_password: true
        
when@test:
    framework:
        validation:
            not_compromised_password: false
