parameters:
    appVersion: '%env(APP_VERSION)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # automatically injects dependencies in your services.
        autoconfigure: true # automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # --------------------------------------------------------------------------------- #
    # error handeling controller for error manager
    Symfony\Component\HttpKernel\EventListener\ErrorListener:
        arguments:
            $controller: 'App\Controller\ErrorController::show'

    # internal exception error event
    App\Event\Subscriber\ExceptionEventSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # resources build checker
    App\Middleware\AssetsCheckMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 8 }

    # escape request data
    App\Middleware\EscapeRequestDataMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 7 }

    # database online checker
    App\Middleware\DatabaseOnlineMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 6 }

    # security check service
    App\Middleware\SecurityCheckMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 5 }

    # maintenance mode checker
    App\Middleware\MaintenanceMiddleware:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 4 }

    # auto login middleware for remember me
    App\Middleware\AutoLoginMiddleware:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 3 }

    # authentificated check middleware
    App\Middleware\AuthentificatedCheckMiddleware:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 2 }

    # user banned check middleware
    App\Middleware\BannedCheckMiddleware:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 1 }
