# deploy app to the production server
name: Deploy

on:
  release:
    types: [created]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # code checkout
    - name: Checkout code
      uses: actions/checkout@v2

    # deploy to the server using SSH
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22

        # script to run on the server
        script: |
          # go to the project directory
          cd /services/website/admin-suite

          # stop apache and clear cache
          sudo systemctl stop apache2
          sudo systemctl stop admin-suite-monitoring
          sudo sh scripts/clear.sh
                   
          # pull the latest changes
          git pull

          # set the environment to production
          sed -i 's/^\(APP_ENV=\)dev/\1prod/' .env

          # install dependencies
          sh scripts/install.sh

          # run database migrations
          mkdir migrations
          php bin/console doctrine:database:create --if-not-exists
          php bin/console make:migration --no-interaction
          php bin/console doctrine:migrations:migrate --no-interaction
                    
          # run app commands
          php bin/console app:auth:tokens:regenerate

          # set permissions
          sudo chmod -R 777 var/
          sudo chown -R www-data:www-data var/

          # start apache
          sudo systemctl start apache2
          sudo systemctl start admin-suite-monitoring
