name: PHPStan

on:
  push:
    branches:
      - main
      - dev

jobs:
  phpstan:
    name: PHPStan analyse
    runs-on: ubuntu-latest

    # phpstan test process
    steps:
    # checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # set up PHP environment
    - name: Set up PHP
      uses: shivammathur/setup-php@v2

    # install project dependencies
    - name: Install dependencies
      run: composer install

    # run PHPStan analysis
    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse --configuration phpstan.neon
